---
name: Savannah
surname: Hammerton
position: "Graduate Student"
address: "University of Georgia College of Public Health, Department of Epidemiology & Biostatistics"
phone: +1 423 544 2453
www: mariecurie.com #remove or put link to portfolio
email: "Savannah.Hammerton@uga.edu"
twitter: smhammerton
github: smhammerton
linkedin: smhammerton
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Some stuff about me

 * I poisoned myself doing research.
 * I was the first woman to win a Nobel prize
 * I was the first person and only woman to win a Nobel prize in two different sciences.

# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Master of Science, Epidemiology & Biostatistics and Graduate Certificate in Infectious Disease Epidemiology", "2020-Present", "University of Georgia", "Athens, GA",
  "Bachelor of Science, Health Science", "2018-2020", "Columbus State University", "Columbus, GA",
  "Diploma, Practical Nursing (summa cum laude)",  "2014-2015", "Chattanooga College", "Chattanooga, TN"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Nobel Prizes

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  2021, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
) %>% 
  brief_entries(
    glue::glue("Nobel Prize in {Type}"),
    Year, 
    Desc
  )
```

# Projects

```{r}
tribble(
  ~ Year, ~ Title, ~ Role, ~ Where,
  "2021", "Prenatal exposure to flame retardants and adverse pregnancy outcomes: A systematic review (in progress)", "Co-Author", "University of Georgia"
) %>% 
  detailed_entries(Year, Role, Title, Where)
```

