---
name: Savannah
surname: Hammerton
position: "Graduate Student"
address: "University of Georgia College of Public Health"
phone: 423 544-2453 
email: 'savannah.hammerton@uga.edu'
github: smhammerton
linkedin: smhammerton
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(googledrive)
library(readxl)
library(tibble)
#googledrive::drive_download('cv_data', overwrite = TRUE)
cv_data <- readxl::read_xlsx('cv_data.xlsx')
```

# Some stuff about me

 * I poisoned myself doing research.
 * I was the first woman to win a Nobel prize
 * I was the first person and only woman to win a Nobel prize in two different sciences.

# Education

```{r education}
cv_data %>% 
  filter(section == 'education', in_resume == 'TRUE') %>% 
  detailed_entries(
    title,
    paste0(start, "-", as.integer(end)),
    institution, 
    loc
  )
```

# Research

```{r}
cv_data %>% 
  filter(section == 'projects', in_resume == 'TRUE') %>% 
  detailed_entries(
    institution, 
    end,
    title,
    description
  )

```

# Relevant Experience 

```{r experience}
cv_data %>% 
  filter(section == 'rel_exp', in_resume == 'TRUE') %>% 
  detailed_entries(
    title,
    paste0(start, "-", as.integer(end)),
    institution, 
    loc,
    description
  )
```

# Certifications

```{r certifications}
cv_data %>% 
  filter(section == 'certs', in_resume == 'TRUE') %>%
  detailed_entries(
    loc,
    end, 
    title
  )
```

# Skills

```{r skills}
cv_data %>% 
  filter(section == 'skills', in_resume == 'TRUE') %>% 
  detailed_entries(
    description,
    NA,
    title
  )
```

