---
name: Savannah
surname: Hammerton
position: "Graduate Student, Epidemiology & Biostatistics"
address: "University of Georgia College of Public Health"
phone: 423 544 2453 
email: 'savannah.hammerton@uga.edu'
github: smhammerton
linkedin: smhammerton
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(googledrive)
library(readxl)
library(tibble)
#googledrive::drive_download('cv_data', overwrite = TRUE)
cv_data <- readxl::read_xlsx('cv_data.xlsx')
```

# Personal Statement  

\setlength\parindent{24pt} I have learned more than I ever expected in my time in the Department of Epidemiology and Biostatistics at the University of Georgia. As I have worked in my classes for this degree, I have found that the more I learn, the more I realize I don’t know. I have also found that I have a strong desire to build expertise in this field. To that end, I am applying to the PhD program in Epidemiology and Biostatistics, with a concentration in Data Analysis and Modeling. 

\setlength\parindent{24pt} I have particular interest in the epidemiology of infectious diseases, and I have worked to develop expertise in this area during my master's program. I hope to continue this development throughout my doctoral program. I am completing the requirements for the Graduate Certificate in Infectious Disease Epidemiology this semester, and am using my master's thesis to focus on infectious disease as well. My thesis is focused on assessing what antibody levels confer protection against norovirus infection, using logistic regression and regularization methods such as LASSO. I am a member of the Center for the Ecology of Infectious Diseases (CEID) at UGA, and joined with the hope of gaining more experience through my work there. My membership will also allow me to utilize my existing knowledge to advance infectious disease research. I plan to continue this focus in my PhD program. My research interests include all infectious disease epidemiology, infectious disease dynamics, and the One Health approach, in particular, zoonotic diseases and spillover events. 
I aim to study these topics by developing conceptual understanding of the various factors contributing to disease spread, and applying that knowledge to strong epidemiological, biostatistical, and modeling methods. 

\setlength\parindent{24pt} One of the factors that encouraged me to apply to this program is the crossover of required coursework between the MS and PhD programs. I have been very successful in my courses this Fall, taking many classes that are required for the PhD. My ability to perform in the upper portion of my classes gives me confidence that I can will be successful in the PhD program. My experience prior to the start of my graduate studies adds to my appreciation of the context and importance of public health problems. My time as a nurse in pediatric home health and inpatient psychiatric care gave me first-hand experiences in many of the areas frequently discussed when solving public health issues, such as the importance of strong public health infrastructure and potential challenges in intervention implementation. These experiences inform all my efforts in public health, and will continue to do so through my academic and professional career. 

\setlength\parindent{24pt} I have felt very fortunate during my time so far in this department to work with such wonderful faculty members. My work with Dr. Handel on my thesis, as well as his classes I have taken, has helped me progress in my skills in data analysis and modeling beyond what I ever hoped for, while also raising my hopes and expectations to continue to progress beyond where I am now. I believe I could meet this goal by continuing to work with and learn from him in any capacity. My work with Dr. Handel is also a driving force behind choosing Data Analysis and Modeling as my area of emphasis. I am confidant that developing my skill set in this area will allow me to approach public health problems in a unique and important way. Particularly in the area of infectious disease dynamics, a solid background in data analysis and modeling will be invaluable in answering important health questions and assessing risk in large populations.

\setlength\parindent{24pt} Working with Dr. Cordero on his environmental exposures and preterm birth review has allowed me the opportunity to gain additional experience in planning a paper from start to finish and assessing current knowledge on a topic as well as the associated gaps in the literature. I have also enjoyed studying the impact of environmental exposures on human health, and would love to continue working with him this. Continuing on to my PhD would also give me the opportunity to work with faculty that I have not yet had as much opportunity to work with. In particular, I find Dr. Winter's research fascinating, and I would be eager to learn more about her work in infectious disease transmission and serological surveillance. 

\setlength\parindent{24pt} I will require financial support to complete my PhD. My time in the master's program in the Department of Epidemiology and Biostatistics has been wonderful and has helped me develop a strong basis of epidemiolgical, biostatistical, and data analysis methodologies. The PhD program will allow me to build on this basis and become the best public health professional possible. I will also work to become an asset that the department can be proud of. Thank you for your time and consideration. 


\makecvfooter{November 2021}{Savannah Hammerton~~~·~~~Personal Statement}{1}